### ISSUE TITLE
The synthesis  wav is bad

### ISSUE THREAD

**Issue by mnfutao** [cyhuang-tw/AutoVC#1]
Hello Sir, thank you very much for your sharing.

I tested it with your pre_train model and it didn't work very well. Even if the two inputs use the same audio, the effect is still poor. Have you encountered such a problem?

**Comment by cyhuang-tw** [comment]
Hi,

Sorry for the late reply. The provided pre-trained model was not tested carefully, with only some examples in VCTK Corpus, and it worked to some extent. Maybe it does not work well on other audios.
Also, I want to know what audios did you use (for example, from which dataset), since it has been shown that AutoVC does not generalize well to other datasets [(reference)](https://arxiv.org/abs/2011.12063).
If you want to use AutoVC for other datasets, maybe it is necessary to adjust the information bottleneck (as its author indicated) for better performance.

**Comment by mnfutao** [comment]
Thank you for your reply！
The data set I used was AISHELL 3 and the results of the paper could not be reproduced.
Thank you for your guidance. I will pay attention to Adain-VC mentioned in the paper and try to reproduce it.
